server:
  port: 8082
spring:
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: mdcuekziqxrybcbc
    # 发送者邮箱地址
    username: 757617711@qq.com
    # 端口（不同邮箱端口号不同）
    port: 25

  rabbitmq:
    username: guest
    password: guest
    # 服务器地址
    host: 121.40.140.4
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual

  redis:
    host: 121.40.140.4
    #    连接超时时间
    timeout: 10000ms
    port: 6379
    database: 0
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒
        max-wait: 10000ms
        # 最大空闲连接 默认 8
        max-idle: 200
        # 最小空闲连接 默认 0
        min-idle: 5

